version: "3"

services:
  balancer:
    container_name: traffic_balancer
    build:
      context: .
      dockerfile: lb.Dockerfile
    environment:
      PORT: "8080"
      REDIS_ADDRESS: "hosts_redis:6379"
      REDIS_DB: 0
      MAX_PARALLEL_REQUESTS: 5
      RESET_INTERVAL: 30s
      BASE_SERVICE_NAME: loadbalancer-s_serv
      TARGET_SERVICE_PORT: 8000
    ports:
      - "8080:8080"

  s_serv:
    build:
      context: .
      dockerfile: sb.Dockerfile

  redis:
    container_name: hosts_redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis_cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/redis

volumes:
  redis_data:
